Repository flintlib/python-flint, pull requests merged in 2024-09, with the labels that each got.

#208 Update docs for install, build and dev workflow
  bin/cibw_before_all_windows.sh
  doc/source/build.rst
  doc/source/index.rst
  doc/source/install.rst
  doc/source/setup.rst
  doc/source/workflow.rst
  meson.build
Labels: type: documentation

#211 Small changes to please cython-lint
  pyproject.toml
  src/flint/flint_base/flint_base.pyx
  src/flint/functions/showgood.pyx
  src/flint/test/test_all.py
  src/flint/types/acb.pyx
  src/flint/types/acb_mat.pyx
  src/flint/types/acb_poly.pyx
  src/flint/types/acb_series.pyx
  src/flint/types/arb.pyx
  src/flint/types/arb_poly.pyx
  src/flint/types/arb_series.pyx
  src/flint/types/fmpq.pyx
  src/flint/types/fmpq_mat.pyx
  src/flint/types/fmpq_series.pyx
  src/flint/types/fmpz.pyx
  src/flint/types/fmpz_mat.pyx
  src/flint/types/fmpz_mod_mat.pxd
  src/flint/types/fmpz_mod_poly.pyx
  src/flint/types/fmpz_series.pyx
  src/flint/types/fq_default.pxd
  src/flint/types/fq_default.pyx
  src/flint/types/fq_default_poly.pyx
  src/flint/types/nmod_mat.pyx
  src/flint/types/nmod_poly.pyx
Labels: type: code quality

#216 Add mpoly docs, functions for discriminant, resultant, term_content, and deflation, and run mod_mpoly doctests.
  doc/source/fmpq_mpoly.rst
  doc/source/fmpz_mod_mpoly.rst
  doc/source/fmpz_mpoly.rst
  doc/source/index.rst
  doc/source/nmod_mpoly.rst
  src/flint/flint_base/flint_base.pxd
  src/flint/flint_base/flint_base.pyx
  src/flint/flintlib/types/nmod.pxd
  src/flint/flintlib/types/undocumented.pxd
  src/flint/test/__main__.py
  src/flint/test/meson.build
  src/flint/test/test_all.py
  src/flint/test/test_docstrings.py
  src/flint/types/arb.pyx
  src/flint/types/fmpq_mpoly.pyx
  src/flint/types/fmpq_vec.pyx
  src/flint/types/fmpz_mod.pyx
  src/flint/types/fmpz_mod_mpoly.pyx
  src/flint/types/fmpz_mod_poly.pyx
  src/flint/types/fmpz_mpoly.pyx
  src/flint/types/fmpz_poly.pyx
  src/flint/types/fmpz_vec.pyx
  src/flint/types/fq_default_poly.pyx
  src/flint/types/nmod_mat.pyx
  src/flint/types/nmod_mpoly.pyx
Labels: type: new feature

#223 docs: use latest Flint when building docs
  .github/workflows/buildwheel.yml
  .readthedocs.yaml
  bin/install_latest_flint_ubuntu.sh
  bin/rtd_before_all_linux.sh
  doc/source/nmod_mpoly.rst
Labels: type: documentation

#212 rename l_function method name
  pyproject.toml
  src/flint/types/dirichlet.pyx
Labels: type: code quality

#225 Improve mpoly context interface
  src/flint/flint_base/flint_base.pxd
  src/flint/flint_base/flint_base.pyx
  src/flint/test/test_all.py
  src/flint/types/fmpq_mpoly.pyx
  src/flint/types/fmpz_mod_mpoly.pxd
  src/flint/types/fmpz_mod_mpoly.pyx
  src/flint/types/fmpz_mpoly.pyx
  src/flint/types/nmod_mpoly.pxd
  src/flint/types/nmod_mpoly.pyx
Labels: type: new feature

#218 Initial bindings for generic rings
  README.md
  bin/all_rst_to_pxd.sh
  bin/rst_to_pxd.py
  doc/source/_gr.rst
  doc/source/conf.py
  doc/source/index.rst
  requirements-dev.txt
  src/flint/flint_base/flint_base.pxd
  src/flint/flintlib/functions/gr.pxd
  src/flint/flintlib/functions/gr_domains.pxd
  src/flint/flintlib/functions/gr_generic.pxd
  src/flint/flintlib/functions/gr_implementing.pxd
  src/flint/flintlib/functions/gr_mat.pxd
  src/flint/flintlib/functions/gr_mpoly.pxd
  src/flint/flintlib/functions/gr_poly.pxd
  src/flint/flintlib/functions/gr_special.pxd
  src/flint/flintlib/functions/gr_vec.pxd
  src/flint/flintlib/types/flint.pxd
  src/flint/flintlib/types/gr.pxd
  src/flint/types/_gr.pxd
  src/flint/types/_gr.pyx
  src/flint/types/meson.build
  src/flint/utils/flint_exceptions.py
Labels: type: new feature

#227 Bump version to 0.7.0a5
  doc/source/_gr.rst
  doc/source/conf.py
  pyproject.toml
  src/flint/__init__.py
  src/flint/test/test_all.py
  src/flint/types/_gr.pxd
  src/flint/types/_gr.pyx
Labels: type: release

#228 Add some mpoly context util functions
  src/flint/flint_base/flint_base.pxd
  src/flint/flint_base/flint_base.pyx
  src/flint/flintlib/types/flint.pxd
  src/flint/test/test_all.py
  src/flint/types/fmpq_mpoly.pyx
  src/flint/types/fmpz_mod_mpoly.pyx
  src/flint/types/fmpz_mpoly.pyx
  src/flint/types/nmod_mpoly.pyx
Labels: type: new feature
